(() => {
  let connectionPollTimer=null, connectionRequestRunning=false;
  function ensureStyle(){if(document.querySelector("link[data-robot-style]"))return;const l=document.createElement("link");l.rel="stylesheet";l.href="admin-robot.css";l.dataset.robotStyle="1";document.head.appendChild(l)}
  function ensureShell(){const nav=document.querySelector(".admin-tabs"),app=document.querySelector("#adminApp");if(!nav||!app)return null;let b=nav.querySelector('[data-tab="robot"]');if(!b){b=document.createElement("button");b.type="button";b.className="tab-button";b.dataset.tab="robot";b.textContent="WhatsApp";b.onclick=()=>{if(typeof switchTab==="function")switchTab("robot")};nav.appendChild(b)}let panel=document.querySelector("#tab-robot");if(!panel){panel=document.createElement("section");panel.className="tab-panel";panel.id="tab-robot";panel.innerHTML='<div class="panel-heading"><div><span>MENSAGENS</span><h2>WhatsApp automático</h2></div></div><div id="robotPanel"></div>';const note=app.querySelector(".security-note");if(note)app.insertBefore(panel,note);else app.appendChild(panel)}return panel.querySelector("#robotPanel")}
  async function connectionApi(options={}){if(typeof api==="function")return api("/api/robot/connection",options);const headers={...(options.headers||{})},token=typeof getAdminAppToken==="function"?getAdminAppToken():"";if(token)headers["x-admin-app-token"]=token;const r=await fetch("/api/robot/connection",{...options,headers,cache:"no-store",credentials:"include"}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Não foi possível consultar a conexão do WhatsApp.");return d}
  function maskPhone(v){let d=String(v||"").replace(/\D/g,"");if(d.startsWith("55")&&d.length>11)d=d.slice(2);d=d.slice(0,11);if(d.length<=2)return d;const a=d.slice(0,2),b=d.slice(2);if(b.length<=4)return`(${a}) ${b}`;if(b.length<=8)return`(${a}) ${b.slice(0,4)}-${b.slice(4)}`;return`(${a}) ${b.slice(0,5)}-${b.slice(5)}`}
  function code(v){const x=String(v||"").replace(/\s+/g,"").trim();return x?(x.match(/.{1,4}/g)?.join(" ")||x):""}
  function render(host,data={}){const badge=host.querySelector("#robotConnectionBadge"),msg=host.querySelector("#robotConnectionMessage"),qr=host.querySelector("#robotQrBox"),img=host.querySelector("#robotQrImage"),codeBox=host.querySelector("#robotPairResult"),codeValue=host.querySelector("#robotPairCode"),reset=host.querySelector("#robotConnectionReset");badge.className="robot-connection-badge";qr.hidden=true;img.removeAttribute("src");codeBox.hidden=true;codeValue.textContent="";reset.disabled=!data.configured;reset.textContent="Gerar QR Code";
    if(!data.configured){badge.classList.add("is-neutral");badge.textContent="Serviço não vinculado";msg.textContent=data.message||"O serviço 24 horas ainda precisa ser vinculado a este sistema.";return}
    if(data.connected){badge.classList.add("is-connected");badge.textContent="WhatsApp conectado";msg.textContent="Conexão ativa. A sessão fica salva e o serviço tenta se reconectar sozinho após reinicializações ou quedas temporárias.";reset.textContent="Trocar WhatsApp por QR Code";return}
    if(data.pairingCode){badge.classList.add("is-waiting");badge.textContent="Código temporário pronto";msg.textContent="Digite o código abaixo no WhatsApp da lanchonete. Se expirar, gere outro.";codeValue.textContent=code(data.pairingCode);codeBox.hidden=false;return}
    if(["preparing-code","pairing-code"].includes(String(data.authState||"").toLowerCase())){badge.classList.add("is-preparing");badge.textContent="Gerando código";msg.textContent="Preparando o código temporário para conectar com o número de telefone...";return}
    if(data.qrReady&&data.qrImage){badge.classList.add("is-waiting");badge.textContent="QR Code pronto";msg.textContent="Escaneie o QR Code abaixo ou use a conexão por código temporário.";img.src=data.qrImage;qr.hidden=false;reset.textContent="Gerar outro QR Code";return}
    if(data.authState==="unreachable"||data.authState==="error"){badge.classList.add("is-error");badge.textContent="Conexão indisponível";msg.textContent=String(data.error||data.lastError||"")||"Não foi possível acessar o serviço agora. O robô continuará tentando se recuperar automaticamente.";reset.textContent="Tentar novamente por QR Code";return}
    badge.classList.add("is-preparing");badge.textContent="Preparando conexão";msg.textContent="Aguarde alguns segundos. Esta tela será atualizada automaticamente."}
  async function load(host,quiet=false){if(!host||connectionRequestRunning)return;connectionRequestRunning=true;const b=host.querySelector("#robotConnectionRefresh"),st=host.querySelector("#robotConnectionActionStatus");if(!quiet)b.disabled=true;try{render(host,await connectionApi());if(st&&!st.dataset.locked){st.className="status";st.textContent=""}}catch(e){render(host,{configured:true,authState:"unreachable",error:e.message})}finally{connectionRequestRunning=false;b.disabled=false}}
  function panel(){ensureStyle();const host=ensureShell();if(!host||host.dataset.robotReady==="1")return host;host.dataset.robotReady="1";host.innerHTML=`<section class="robot-admin-card robot-connection-card"><div class="robot-admin-header"><div><h2>Conexão do WhatsApp</h2><p>Use QR Code ou o código temporário pelo número de telefone. Esta conexão serve somente para enviar pedidos e avisos automáticos.</p></div><span class="robot-connection-badge is-preparing" id="robotConnectionBadge">Verificando</span></div><p class="robot-connection-message" id="robotConnectionMessage">Consultando o serviço do WhatsApp...</p><div class="robot-pair-box"><strong>Conectar com código temporário</strong><p>Informe o número do WhatsApp da lanchonete e gere o código para digitar no próprio WhatsApp.</p><div class="robot-pair-row"><input id="robotPairPhone" type="tel" inputmode="tel" maxlength="16" placeholder="(92) 99999-9999"><button type="button" class="admin-primary" id="robotGeneratePairCode">Gerar código temporário</button></div><div class="robot-pair-result" id="robotPairResult" hidden><small>CÓDIGO TEMPORÁRIO</small><strong id="robotPairCode"></strong><p>WhatsApp → Aparelhos conectados → Conectar um aparelho → Conectar com número de telefone → digite este código.</p></div></div><div class="robot-qr-box" id="robotQrBox" hidden><img id="robotQrImage" alt="QR Code para conectar o WhatsApp"><ol><li>Abra o WhatsApp da lanchonete.</li><li>Entre em <strong>Aparelhos conectados</strong>.</li><li>Toque em <strong>Conectar um aparelho</strong> e leia este código.</li></ol></div><div class="robot-actions"><button type="button" class="admin-secondary" id="robotConnectionRefresh">Atualizar estado</button><button type="button" class="admin-primary" id="robotConnectionReset">Gerar QR Code</button></div><p class="status" id="robotConnectionActionStatus" aria-live="polite"></p><p class="robot-stability-note">A sessão é salva no serviço 24h. Em quedas temporárias, o robô tenta recuperar a conexão automaticamente sem exigir novo pareamento.</p></section><section class="robot-admin-card"><div class="robot-admin-header"><div><h2>Mensagens automáticas</h2><p>O envio acontece sozinho. Não é necessário abrir conversas ou tocar novamente no WhatsApp.</p></div><span class="robot-status is-on">● Automático</span></div><div class="robot-note"><strong>O sistema enviará:</strong><ul class="automatic-message-list"><li>o pedido completo para o WhatsApp da lanchonete;</li><li>a confirmação de recebimento para o cliente;</li><li>pedido confirmado;</li><li>pedido saiu para entrega ou está pronto para retirada;</li><li>pedido cancelado.</li></ul></div><div class="robot-note"><strong>Sem atendimento automático:</strong> mensagens que o cliente enviar serão deixadas para a equipe responder normalmente.</div></section>`;
    const phone=host.querySelector("#robotPairPhone");phone.oninput=()=>phone.value=maskPhone(phone.value);setTimeout(()=>{const v=document.querySelector("#businessWhatsappInput")?.value;if(v&&!phone.value)phone.value=maskPhone(v)},1200);
    host.querySelector("#robotGeneratePairCode").onclick=async()=>{const b=host.querySelector("#robotGeneratePairCode"),st=host.querySelector("#robotConnectionActionStatus"),value=document.querySelector("#businessWhatsappInput")?.value||phone.value;if(String(value).replace(/\D/g,"").length<10){st.className="status error";st.textContent="Informe um número de WhatsApp válido com DDD.";return}phone.value=maskPhone(value);b.disabled=true;st.dataset.locked="1";st.className="status";st.textContent="Gerando código temporário...";try{const r=await connectionApi({method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"pair-code",phoneNumber:value})});st.className="status ok";st.textContent=r.message||"Código solicitado. Aguarde alguns segundos.";render(host,{configured:true,authState:"preparing-code"});setTimeout(()=>{delete st.dataset.locked;load(host)},2500)}catch(e){st.className="status error";st.textContent=e.message||"Não foi possível gerar o código temporário.";delete st.dataset.locked}finally{b.disabled=false}};
    host.querySelector("#robotConnectionRefresh").onclick=()=>load(host);host.querySelector("#robotConnectionReset").onclick=async()=>{const connected=host.querySelector("#robotConnectionBadge")?.classList.contains("is-connected");if(connected&&!confirm("Isso desconectará o WhatsApp atual e gerará um novo QR Code. Continuar?"))return;const b=host.querySelector("#robotConnectionReset"),st=host.querySelector("#robotConnectionActionStatus");b.disabled=true;st.dataset.locked="1";st.className="status";st.textContent="Preparando um novo QR Code...";try{const r=await connectionApi({method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"reset"})});st.className="status ok";st.textContent=r.message||"Novo QR Code solicitado.";render(host,{configured:true,authState:"starting"});setTimeout(()=>{delete st.dataset.locked;load(host)},1800)}catch(e){st.className="status error";st.textContent=e.message||"Não foi possível gerar um novo QR Code.";delete st.dataset.locked}finally{b.disabled=false}};
    load(host);connectionPollTimer=setInterval(()=>{if(document.visibilityState!=="visible")return;const p=document.querySelector("#tab-robot");if(p?.classList.contains("active"))load(host,true)},3500);return host}
  window.LanchoneteRobot={renderRobotPanel:panel};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",panel);else panel();
})();
