const http=require('http'),path=require('path'),crypto=require('crypto');const{fork}=require('child_process');
const PORT=Number(process.env.PORT||3000),children=new Map(),states=new Map(),startupTimers=[],pendingMessages=new Map(),pairingPhones=new Map();let shuttingDown=false;
const ADMIN_CONTROL_HASHES=new Map([['lanchonete-whatsapp','c87d431851bb55cddb601e9bd8bd7eadd7bc0f4906e41318e17d63379a23b483'],['lanchonete-2-whatsapp','3c1ff0e77623f56bdf0eda50d37b7c3568ba4c0a17d87763c50d46fe8dcfae1d'],['lanchonete-3-whatsapp','bfcfc09b0c6942fcc6b279a37c51567b95ade470d4f3f218899c225227435c3b']]);
function normalizeInstance(item,index){const name=String(item?.name||`instancia-${index+1}`),raw=String(item?.slug||item?.WPP_SESSION||item?.LANCHONETE_WPP_SESSION||name),slug=raw.trim().toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'');if(!slug)throw new Error(`Identificador inválido para ${name}.`);return{...item,name,slug,ROBOT_CONTROL_TOKEN:String(item?.ROBOT_CONTROL_TOKEN||process.env.ROBOT_CONTROL_TOKEN||''),ROBOT_CONTROL_TOKEN_SHA256:String(item?.ROBOT_CONTROL_TOKEN_SHA256||process.env.ROBOT_CONTROL_TOKEN_SHA256||ADMIN_CONTROL_HASHES.get(slug)||'').trim().toLowerCase()}}
function readInstances(){const raw=String(process.env.ROBOT_INSTANCES_JSON||'').trim();if(!raw){const session=process.env.WPP_SESSION||process.env.LANCHONETE_WPP_SESSION||'lanchonete';return[normalizeInstance({name:session,WPP_SESSION:session},0)]}const parsed=JSON.parse(raw);if(!Array.isArray(parsed)||!parsed.length||parsed.length>4)throw new Error('ROBOT_INSTANCES_JSON deve conter de 1 a 4 configurações.');return parsed.map(normalizeInstance)}
const instances=readInstances();
function terminate(child,signal){if(!child?.pid)return;if(process.platform!=='win32'){try{process.kill(-child.pid,signal);return}catch(_){}}try{child.kill(signal)}catch(_){}}
function startInstance(instance){const{slug:_slug,...childEnvironment}=instance,pairingPhone=String(pairingPhones.get(instance.slug)||'');const child=fork(path.join(__dirname,'index.js'),[],{env:{...process.env,...childEnvironment,WPP_PAIRING_PHONE:pairingPhone,DISABLE_HTTP_SERVER:'1',ROBOT_SUPERVISED:'1',ROBOT_DIRECT_CONTROL:'1'},execArgv:['-r',path.join(__dirname,'pairing-preload.js')],detached:process.platform!=='win32',stdio:['inherit','inherit','inherit','ipc']});children.set(instance.name,child);states.set(instance.slug,{ok:true,connected:false,qrReady:false,qrImage:null,pairingCode:null,authState:pairingPhone?'preparing-code':'starting',connectedAt:null,lastError:null});console.log(`🚀 Iniciando ${instance.name}${pairingPhone?' em modo código temporário':''}.`);
child.on('message',m=>{if(m?.type==='transactional-result'&&m.requestId){const p=pendingMessages.get(String(m.requestId));if(!p)return;pendingMessages.delete(String(m.requestId));clearTimeout(p.timer);m.error?p.reject(new Error(String(m.error))):p.resolve(m.result||{sent:false});return}if(m?.type==='pairing-code'){const c=String(m.code||'').replace(/\s+/g,'').slice(0,32);if(!c)return;const prev=states.get(instance.slug)||{};states.set(instance.slug,{...prev,ok:true,connected:false,qrReady:false,qrImage:null,pairingCode:c,authState:'pairing-code',lastError:null});console.log(`🔐 Código temporário pronto para ${instance.name}.`);return}if(m?.type!=='robot-state'||!m.state||typeof m.state!=='object')return;const prev=states.get(instance.slug)||{},connected=Boolean(m.state.connected);if(connected)pairingPhones.delete(instance.slug);states.set(instance.slug,{ok:true,connected,qrReady:Boolean(m.state.qrReady&&m.state.qrImage),qrImage:m.state.qrImage||null,pairingCode:connected?null:(prev.pairingCode||null),authState:String(m.state.authState||(pairingPhones.has(instance.slug)?'preparing-code':'starting')),connectedAt:m.state.connectedAt||null,lastError:m.state.lastError||null})});
child.on('exit',(code,signal)=>{for(const[id,p]of pendingMessages){if(p.instanceName!==instance.name)continue;pendingMessages.delete(id);clearTimeout(p.timer);p.reject(new Error('A instância do WhatsApp reiniciou durante o envio.'))}children.delete(instance.name);terminate(child,'SIGKILL');states.set(instance.slug,{ok:true,connected:false,qrReady:false,qrImage:null,pairingCode:null,authState:shuttingDown?'stopped':(pairingPhones.has(instance.slug)?'preparing-code':'restarting'),connectedAt:null,lastError:null});console.warn(`⚠️ ${instance.name} encerrou (${signal||code||0}).`);if(!shuttingDown)setTimeout(()=>startInstance(instance),3500).unref()})}
for(const[index,instance]of instances.entries()){if(index===0)startInstance(instance);else startupTimers.push(setTimeout(()=>{if(!shuttingDown)startInstance(instance)},index*12000))}
function sendJson(res,data,status=200){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(data))}
const sha=v=>crypto.createHash('sha256').update(String(v||''),'utf8').digest('hex');function safeEqual(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function authorized(req,instance){const a=String(req.headers.authorization||''),supplied=a.toLowerCase().startsWith('bearer ')?a.slice(7).trim():'';if(!supplied)return false;const expected=String(instance.ROBOT_CONTROL_TOKEN||'');if(expected&&safeEqual(supplied,expected))return true;const h=String(instance.ROBOT_CONTROL_TOKEN_SHA256||'').trim().toLowerCase();return/^[0-9a-f]{64}$/.test(h)&&safeEqual(sha(supplied),h)}
function readJson(req,max=262144){return new Promise((resolve,reject)=>{let size=0;const chunks=[];req.on('data',c=>{size+=c.length;if(size>max){reject(new Error('Corpo da solicitação muito grande.'));req.destroy();return}chunks.push(c)});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}'))}catch{reject(new Error('JSON inválido.'))}});req.on('error',reject)})}
function normalizePhone(v){let d=String(v||'').replace(/\D/g,'');if(d.length===10||d.length===11)d=`55${d}`;return/^55\d{10,11}$/.test(d)?`+${d}`:''}
function forward(instance,action,payload){const child=children.get(instance.name);if(!child?.connected)return Promise.reject(new Error('A instância do WhatsApp está reiniciando.'));const id=crypto.randomUUID();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pendingMessages.delete(id);reject(new Error('O WhatsApp não confirmou o envio a tempo.'))},18000);pendingMessages.set(id,{resolve,reject,timer,instanceName:instance.name});try{child.send({type:'transactional-message',requestId:id,action,payload})}catch(e){pendingMessages.delete(id);clearTimeout(timer);reject(e)}})}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost'),m=url.pathname.match(/^\/instances\/([^/]+)\/control\/(status|restart|reset|pair-code|send-order|send-status)$/);if(m){let slug='';try{slug=decodeURIComponent(m[1])}catch(_){}const action=m[2],instance=instances.find(x=>x.slug===slug);if(!instance)return sendJson(res,{error:'Instância não encontrada.'},404);if(!authorized(req,instance))return sendJson(res,{error:'Não autorizado.'},401);
if(action==='status'){if(req.method!=='GET')return sendJson(res,{error:'Método não permitido.'},405);return sendJson(res,states.get(instance.slug)||{ok:true,connected:false,qrReady:false,pairingCode:null,authState:'starting'})}
if(action==='send-order'||action==='send-status'){if(req.method!=='POST')return sendJson(res,{error:'Método não permitido.'},405);try{const payload=await readJson(req),result=await forward(instance,action,payload);return sendJson(res,{ok:true,...result},result.sent?200:502)}catch(e){return sendJson(res,{error:String(e?.message||e).slice(0,240),sent:false},503)}}
if(action==='pair-code'){if(req.method!=='POST')return sendJson(res,{error:'Método não permitido.'},405);let payload;try{payload=await readJson(req)}catch{return sendJson(res,{error:'Dados inválidos.'},400)}const phone=normalizePhone(payload?.phoneNumber);if(!phone)return sendJson(res,{error:'Informe um número de WhatsApp válido com DDD.'},400);pairingPhones.set(instance.slug,phone);states.set(instance.slug,{ok:true,connected:false,qrReady:false,qrImage:null,pairingCode:null,authState:'preparing-code',connectedAt:null,lastError:null});const child=children.get(instance.name);if(child?.connected){try{child.send({type:'robot-control',action:'reset'})}catch{terminate(child,'SIGKILL')}}else if(child)terminate(child,'SIGKILL');else setTimeout(()=>{if(!shuttingDown&&!children.has(instance.name))startInstance(instance)},250).unref();return sendJson(res,{ok:true,accepted:true,action:'pair-code',message:'Preparando o código temporário. Ele aparecerá no painel em alguns segundos.'},202)}
if(req.method!=='POST')return sendJson(res,{error:'Método não permitido.'},405);pairingPhones.delete(instance.slug);const child=children.get(instance.name);if(!child?.connected)return sendJson(res,{error:'A instância está reiniciando.'},503);const prev=states.get(instance.slug);states.set(instance.slug,{ok:true,connected:false,qrReady:false,qrImage:null,pairingCode:null,authState:action==='reset'?'resetting':'restarting',connectedAt:null,lastError:null});try{child.send({type:'robot-control',action})}catch(_){if(prev)states.set(instance.slug,prev);return sendJson(res,{error:'A instância está reiniciando.'},503)}return sendJson(res,{ok:true,accepted:true,action},202)}
if(url.pathname!=='/'&&url.pathname!=='/health')return sendJson(res,{error:'Not found'},404);const running=instances.map(i=>({name:i.name,running:Boolean(children.get(i.name)?.connected),whatsappConnected:Boolean(states.get(i.slug)?.connected)})),ok=running.every(x=>x.running);sendJson(res,{ok,instances:running},ok?200:503)});
server.listen(PORT,'0.0.0.0',()=>console.log(`🌐 Supervisor ativo na porta ${PORT} com ${instances.length} instância(s).`));function stop(signal){shuttingDown=true;for(const t of startupTimers)clearTimeout(t);for(const c of children.values())terminate(c,signal);server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),5000).unref()}process.on('SIGTERM',()=>stop('SIGTERM'));process.on('SIGINT',()=>stop('SIGINT'));
